name: Maintenance Updates

on:
  workflow_dispatch:

  schedule:
    - cron:  '50 15 10 * *' # 10th of month at 16:50.

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACF_PRO_KEY: ${{ secrets.ACF_PRO_KEY }}

      DB_DATABASE: wordpress
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1

      WP_SITE_URL: wordpress-github-actions-testing.ddev.site
      WP_SITE_TITLE: "Devops Site"
      WP_ADMIN_USERNAME: admin
      WP_ADMIN_EMAIL: admin@example.com

      PLUGIN_DIRECTORY: wp-content/plugins
      THEME_DIRECTORY: wp-content/themes
      LANGUAGE_DIRECTORY: wp-content/languages

      # Detemines whether ACF pro should be updated.
      UPDATE_ACF_PRO: true
      UPDATE_LANGUAGES: true
    steps:
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          sudo mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
        env:
          update: true

      - uses: actions/checkout@v3

      - name: Set Date
        id: vars
        run: |
          full_date=$(date +"%d-%m-%Y")
          branch_date=$(date +"%d-%b-%y")
          branch_name=maintenance/${branch_date,,}
          echo branch_name=$branch_name >> $GITHUB_OUTPUT
          echo date=$full_date >> $GITHUB_OUTPUT

      - name: Perform updates
        uses: jaymeh/wordpress-plugin-updater@feature/creating_action
        id: perform-updates
        with:
          updateAcfPro: true
          acfProKey: ${{ secrets.ACF_PRO_KEY }}
          committerName: Jamie Sykes
          committerEmail: 18261676+jaymeh@users.noreply.github.com

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ steps.vars.outputs.branch_name }}
          commit-message: Update Translations and Languages for plugins, themes and core.
          title: Maintanence updates for ${{ steps.vars.outputs.date }}
          body: ${{ steps.perform-updates.outputs.updateReport }}
